// web/src/components/ChatView.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch } from "vue";
import { store } from "../ws";
import MessageItem from "./MessageItem.vue";
import InputBar from "./InputBar.vue";

const view = computed(() => (store.activeKey ? store.views[store.activeKey] : null));
const scroller = ref<HTMLElement>();

// 滚动位置：每个会话独立记忆，首次进入默认到底部
const SCROLL_KEY = "piflow.scroll";
let scrollMap: Record<string, number> = {};
try {
  scrollMap = JSON.parse(localStorage.getItem(SCROLL_KEY) ?? "{}");
} catch {
  // ponytail: corrupted storage → start fresh
}
let pendingInitial = false;
let saveTimer: ReturnType<typeof setTimeout> | undefined;

function persist(key: string, top: number) {
  scrollMap[key] = top;
  localStorage.setItem(SCROLL_KEY, JSON.stringify(scrollMap));
}

function applyInitial() {
  const el = scroller.value;
  const key = store.activeKey;
  if (!el || !key) {
    pendingInitial = false;
    return;
  }
  // 内容尚未渲染完成时等待下一次 tick
  const v = view.value;
  if (v && v.messages.length > 0 && el.scrollHeight === 0) return;
  const saved = scrollMap[key];
  el.scrollTop = saved != null ? saved : el.scrollHeight;
  pendingInitial = false;
}

function onScroll() {
  const el = scroller.value;
  const key = store.activeKey;
  if (!el || !key) return;
  clearTimeout(saveTimer);
  saveTimer = setTimeout(() => persist(key, el.scrollTop), 200);
  scheduleTitle();
}

// 顶栏跟随：视口内最近的一条用户消息
const liveTitle = ref("");
let titleRaf = 0;

function scheduleTitle() {
  if (titleRaf) return;
  titleRaf = requestAnimationFrame(() => {
    titleRaf = 0;
    updateTitle();
  });
}

function updateTitle() {
  const el = scroller.value;
  if (!el) return;
  const items = el.querySelectorAll<HTMLElement>("[data-user]");
  const threshold = el.scrollTop + 56;
  let current = "";
  for (const node of items) {
    if (node.offsetTop <= threshold) current = node.dataset.user ?? "";
    else break;
  }
  liveTitle.value = current;
}

watch(
  () => store.activeKey,
  async (_new, oldKey) => {
    // 切换前立即落盘旧会话位置
    if (oldKey && scroller.value) persist(oldKey, scroller.value.scrollTop);
    liveTitle.value = "";
    pendingInitial = true;
    await nextTick();
    applyInitial();
    updateTitle();
  },
);

const title = computed(() => {
  const key = store.activeKey;
  if (!key) return "piflow";
  const s = store.sessions.find((s) => s.path === key);
  return s ? s.name || s.firstMessage || "会话" : "新会话";
});

const presets = ["探索这个代码库", "回顾我的改动", "修一个 bug", "做个功能规划"];

// 聊天列宽：860 / 1180 / 1440 三档可调
const WIDTHS = [860, 1180, 1440];
const widthIdx = ref(Math.min(Number(localStorage.getItem("piflow.chatWidth") ?? 1), 2));
const chatW = computed(() => WIDTHS[widthIdx.value]);
function cycleWidth() {
  widthIdx.value = (widthIdx.value + 1) % WIDTHS.length;
  localStorage.setItem("piflow.chatWidth", String(widthIdx.value));
}

function usePreset(p: string) {
  store.draft = p;
}

const isEmpty = computed(() => !view.value || view.value.messages.length === 0);

watch(
  () => view.value?.tick,
  async () => {
    await nextTick();
    if (pendingInitial) {
      applyInitial();
      return;
    }
    const el = scroller.value;
    if (!el) return;
    const nearBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 160;
    if (nearBottom) el.scrollTop = el.scrollHeight;
    updateTitle();
  },
);
</script>

<template>
  <div class="chat" :style="{ '--chat-w': chatW + 'px' }">
    <header class="bar">
      <button class="menu recede" @click="store.sidebarOpen = !store.sidebarOpen">☰</button>
      <span class="title">{{ liveTitle || title }}</span>
      <button class="width recede" title="切换聊天宽度" @click="cycleWidth">⇔</button>
      <span class="status" :class="{ on: view?.isStreaming }" />
    </header>

    <div ref="scroller" class="scroll" :class="{ centered: isEmpty }" @scroll.passive="onScroll">
      <!-- hero：空会话 -->
      <div v-if="isEmpty" class="hero">
        <h1>今天做点什么？</h1>
        <div class="presets">
          <button v-for="p in presets" :key="p" class="pill recede" @click="usePreset(p)">
            {{ p }}
          </button>
        </div>
        <p v-if="!view" class="dim">也可以从左侧选择一个历史会话继续</p>
      </div>

      <!-- 消息流 -->
      <div v-else class="col">
        <MessageItem
          v-for="(m, i) in view!.messages"
          :key="i"
          :message="m"
          :tool-results="view!.toolResults"
        />
        <MessageItem
          v-if="view!.live"
          :message="view!.live"
          :tool-results="view!.toolResults"
          live
        />
        <div v-if="view!.isStreaming && !view!.live" class="pending">
          <span class="dot" />
        </div>
        <div v-if="view!.isCompacting" class="note">正在压缩上下文…</div>
        <div v-if="view!.error" class="error">{{ view!.error }}</div>
      </div>
    </div>

    <InputBar :view="view" />
  </div>
</template>

<style scoped>
.chat {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.bar {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 12px 20px;
  border-bottom: 1px solid var(--c-line);
}

.menu {
  display: none;
  color: var(--c-muted);
  font-size: 1.1rem;
}

.title {
  flex: 1;
  color: var(--c-mid);
  font-size: 0.9rem;
  font-weight: 600;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.width {
  color: var(--c-muted);
  font-size: 0.9rem;
}

.status {
  flex-shrink: 0;
  width: 7px;
  height: 7px;
  border-radius: 50%;
  background: var(--c-faint);
  opacity: 0.4;
  transition: all 0.3s var(--ease);
}

.status.on {
  background: var(--c-signal);
  opacity: 1;
  animation: pulse 1.6s var(--ease) infinite;
}

@keyframes pulse {
  50% { opacity: 0.35; }
}

.scroll {
  position: relative;
  flex: 1;
  overflow-y: auto;
}

.scroll.centered {
  display: flex;
  align-items: center;
  justify-content: center;
}

.col {
  width: min(calc(100% - 48px), var(--chat-w));
  margin: 0 auto;
  padding: 24px 0 16px;
  transition: width 0.25s var(--ease);
}

/* hero */

.hero {
  text-align: center;
  padding: 40px 20px;
}

.hero h1 {
  margin: 0 0 24px;
  color: var(--c-mid);
  font-size: 1.75rem;
  font-weight: 700;
  line-height: 1.2;
  letter-spacing: -0.01em;
}

.presets {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 8px;
  max-width: 480px;
  margin: 0 auto;
}

.pill {
  padding: 6px 14px;
  border: 1px solid var(--c-line);
  border-radius: 999px;
  color: var(--c-muted);
  font-size: 0.85rem;
  transition: border-color 0.2s var(--ease), opacity 0.2s var(--ease);
}

.pill:hover {
  border-color: var(--c-faint);
}

.hero .dim {
  margin-top: 24px;
  color: var(--c-faint);
  font-size: 0.82rem;
}

/* streaming indicators */

.pending {
  padding: 8px 0;
}

.dot {
  display: inline-block;
  width: 7px;
  height: 7px;
  border-radius: 50%;
  background: var(--c-signal);
  animation: pulse 1.2s var(--ease) infinite;
}

.note {
  color: var(--c-muted);
  font-size: 0.85rem;
  padding: 8px 0;
}

.error {
  color: #ffa198;
  font-size: 0.85rem;
  padding: 8px 0;
}

@media (max-width: 768px) {
  .menu { display: block; }
  .width { display: none; }
  .col { width: calc(100% - 32px); }
}
</style>

// packages/web/src/components/ChatView/index.tsx
import type { ChatMessage } from '@piflow/protocol'
import type { CSSProperties, UIEvent, WheelEvent } from 'react'
import { PanelLeft } from 'lucide-react'
import { useEffect, useLayoutEffect, useRef, useState } from 'react'
import { setSidebarOpen } from '../../session/store'
import { useStore } from '../../session/use-store'
import InputBar from '../InputBar'
import MessageItem from '../MessageItem'
import ViewSwitch from '../ViewSwitch'
import styles from './styles.module.css'

const SCROLL_KEY = 'piflow.scroll'
const PRESETS = ['探索这个代码库', '回顾我的改动', '修一个 bug', '做个功能规划']
const WIDTHS = [860, 1180, 1440] as const
const messageIds = new WeakMap<ChatMessage, number>()
let nextMessageId = 1

function readScrollMap(): Record<string, number> {
  try {
    return JSON.parse(localStorage.getItem(SCROLL_KEY) ?? '{}')
  }
  catch {
    return {}
  }
}

interface ChatViewProps {
  onShowFlow: () => void
  onToggleSidebar: () => void
  sidebarCollapsed: boolean
}

export default function ChatView({ onShowFlow, onToggleSidebar, sidebarCollapsed }: ChatViewProps) {
  const store = useStore()
  const view = store.activeKey ? (store.views[store.activeKey] ?? null) : null
  const scrollerRef = useRef<HTMLDivElement>(null)
  const scrollMapRef = useRef(readScrollMap())
  const stickToBottomRef = useRef(true)
  const programmaticScrollRef = useRef(false)
  const userScrollRef = useRef(false)
  const userScrollTimerRef = useRef<ReturnType<typeof setTimeout>>(undefined)
  const saveTimerRef = useRef<ReturnType<typeof setTimeout>>(undefined)
  const previousKeyRef = useRef<string | null>(null)
  const rafRef = useRef<number | null>(null)
  const resizeObserverRef = useRef<ResizeObserver | null>(null)
  const [column, setColumn] = useState<HTMLDivElement | null>(null)
  const [composerText, setComposerText] = useState('')
  const [composerFocusVersion, setComposerFocusVersion] = useState(0)
  const [widthIndex, setWidthIndex] = useState(() => Math.min(Number(localStorage.getItem('piflow.chatWidth') ?? 1), 2))
  const session = store.sessions.find(session => session.path === store.activeKey)
  const title = store.activeKey ? session?.name || session?.firstMessage || '新会话' : ''

  function persist(key: string, top: number) {
    scrollMapRef.current[key] = top
    localStorage.setItem(SCROLL_KEY, JSON.stringify(scrollMapRef.current))
  }

  function onScroll(event: UIEvent<HTMLDivElement>) {
    if (programmaticScrollRef.current)
      return
    markUserScroll()
    const key = store.activeKey
    if (!key)
      return
    const element = event.currentTarget
    clearTimeout(saveTimerRef.current)
    saveTimerRef.current = setTimeout(persist, 200, key, element.scrollTop)
    stickToBottomRef.current = element.scrollHeight - element.scrollTop - element.clientHeight < 160
  }

  function markUserScroll() {
    userScrollRef.current = true
    clearTimeout(userScrollTimerRef.current)
    userScrollTimerRef.current = setTimeout(() => {
      userScrollRef.current = false
    }, 200)
  }

  function onWheel(event: WheelEvent<HTMLDivElement>) {
    if (event.deltaY < 0)
      stickToBottomRef.current = false
    markUserScroll()
  }

  useLayoutEffect(() => {
    const element = scrollerRef.current
    const oldKey = previousKeyRef.current
    if (oldKey && element)
      persist(oldKey, element.scrollTop)
    previousKeyRef.current = store.activeKey
    if (element && store.activeKey) {
      programmaticScrollRef.current = true
      element.scrollTop = scrollMapRef.current[store.activeKey] ?? element.scrollHeight
      stickToBottomRef.current = element.scrollHeight - element.scrollTop - element.clientHeight < 160
      requestAnimationFrame(() => {
        programmaticScrollRef.current = false
      })
    }
  }, [store.activeKey])

  // Anchor scroll to the bottom while streaming, but only when the user is already near the bottom.
  // ResizeObserver batches content changes and requestAnimationFrame throttles the scroll update.
  useEffect(() => {
    const scroller = scrollerRef.current
    if (!scroller || !column)
      return

    function anchor() {
      if (!stickToBottomRef.current || userScrollRef.current)
        return
      programmaticScrollRef.current = true
      scroller!.scrollTop = scroller!.scrollHeight
      requestAnimationFrame(() => {
        programmaticScrollRef.current = false
      })
    }

    const observer = new ResizeObserver(() => {
      if (rafRef.current) {
        cancelAnimationFrame(rafRef.current)
        rafRef.current = null
      }
      rafRef.current = requestAnimationFrame(anchor)
    })

    resizeObserverRef.current = observer
    observer.observe(column)

    return () => {
      observer.disconnect()
      resizeObserverRef.current = null
      if (rafRef.current) {
        cancelAnimationFrame(rafRef.current)
        rafRef.current = null
      }
    }
  }, [column, store.activeKey])

  // Re-anchor to bottom after window resize when the user is already near the bottom.
  useEffect(() => {
    function handleResize() {
      const element = scrollerRef.current
      if (!element)
        return
      const nearBottom = element.scrollHeight - element.scrollTop - element.clientHeight < 160
      stickToBottomRef.current = nearBottom
      if (!nearBottom)
        return
      programmaticScrollRef.current = true
      element.scrollTop = element.scrollHeight
      requestAnimationFrame(() => {
        programmaticScrollRef.current = false
      })
    }
    let timer: ReturnType<typeof setTimeout> | undefined
    function onResize() {
      clearTimeout(timer)
      timer = setTimeout(handleResize, 100)
    }
    window.addEventListener('resize', onResize)
    return () => {
      window.removeEventListener('resize', onResize)
      clearTimeout(timer)
    }
  }, [])

  const isEmpty = !view || view.messages.length === 0
  const chatStyle = { '--chat-w': `${WIDTHS[widthIndex] ?? WIDTHS[1]}px` } as CSSProperties
  const isLive = store.connected && !!view?.isStreaming
  const statusLabel = !store.connected
    ? '连接中…'
    : view?.isCompacting
      ? '压缩上下文'
      : isLive
        ? '生成中'
        : ''

  function applyPreset(preset: string) {
    setComposerText(preset)
    setComposerFocusVersion(version => version + 1)
  }

  function cycleWidth() {
    setWidthIndex((current) => {
      const next = (current + 1) % WIDTHS.length
      localStorage.setItem('piflow.chatWidth', String(next))
      return next
    })
  }

  return (
    <div className={styles.chat} style={chatStyle}>
      <header className={styles.bar}>
        {sidebarCollapsed ? <button className={styles.menu} title="展开会话列表" aria-label="展开会话列表" onClick={onToggleSidebar}><PanelLeft size={15} /></button> : null}
        <button className={styles.mobileMenu} title="会话列表" aria-label="切换会话列表" onClick={() => setSidebarOpen(!store.sidebarOpen)}><PanelLeft size={15} /></button>
        <div className={styles.identity}>
          {title ? <div className={styles.title} title={title}>{title}</div> : null}
        </div>
        <div className={styles.actions}>
          <span className={`${styles.status} ${statusLabel ? styles.on : ''}`}>{statusLabel}</span>
          <ViewSwitch active="chat" onChange={view => view === 'flow' && onShowFlow()} />
          <button className={styles.width} title="切换聊天宽度" aria-label="切换聊天宽度" onClick={cycleWidth}>⇔</button>
        </div>
      </header>

      <div ref={scrollerRef} className={`${styles.scroll} ${isEmpty ? styles.centered : ''}`} onScroll={onScroll} onWheel={onWheel}>
        {isEmpty
          ? (
              <div className={styles.hero}>
                <h1>今天做点什么？</h1>
                <div className={styles.presets}>
                  {PRESETS.map(preset => (
                    <button key={preset} className={styles.pill} onClick={() => applyPreset(preset)}>{preset}</button>
                  ))}
                </div>
                {!view ? <p className={styles.dim}>也可以从左侧选择一个历史会话继续</p> : null}
              </div>
            )
          : (
              <div ref={setColumn} className={styles.column}>
                {view.messages.map(message => (
                  <MessageItem
                    key={messageKey(message)}
                    message={message}
                    toolResults={view.toolResults}
                  />
                ))}
                {view.live ? <MessageItem message={view.live} toolResults={view.toolResults} live /> : null}
                {isLive && !view.live
                  ? (
                      <div className={styles.pending}>
                        <span className={styles.dot} />
                        正在生成…
                      </div>
                    )
                  : null}
                {store.connected && view.isCompacting ? <div className={styles.note}>正在压缩上下文…</div> : null}
                {view.error ? <div className={styles.error}>{view.error}</div> : null}
              </div>
            )}
      </div>

      <InputBar
        view={view}
        text={composerText}
        focusVersion={composerFocusVersion}
        onTextChange={setComposerText}
      />
    </div>
  )
}

function messageKey(message: ChatMessage) {
  let id = messageIds.get(message)
  if (!id) {
    id = nextMessageId++
    messageIds.set(message, id)
  }
  return `${message.role}:${message.timestamp ?? 'untimed'}:${id}`
}
